In [101]:
import numpy as np
import pandas as pd
from matplotlib import pyplot as plt

In [102]:
ar = [1,2,3,4]
arr = np.array(ar)
print(arr)

[1 2 3 4]


In [103]:
print(arr[::-1])

[4 3 2 1]


In [104]:
arr1 = [1,2,3.1]
arr2 = np.array(arr1)
print(arr2)

[1.  2.  3.1]


In [118]:
arr1 = np.array([1,2,3,4])
arr2 = np.copy(arr1)
arr1[0] = 10
print(arr2)
print(arr1)

[1 2 3 4]
[10  2  3  4]


In [106]:
arr1 = np.array([1,2,3,4])
arr2 = arr1.view()
arr1[0] = 10
print(arr2)
print(arr1)

[10  2  3  4]
[10  2  3  4]


In [120]:
arr1.shape = 2,2
print(np.shape(arr1))

(2, 2)


In [108]:
arr1.reshape((4,1))

array([[10],
       [ 2],
       [ 3],
       [ 4]])

In [109]:
a = np.array([1,2,3,4,5])
for i in a:
    print(i, end = ',')

1,2,3,4,5,

In [110]:
a = np.array([1,2,3,4,5])
b = np.array([6,7,8,9,10])
c = np.concatenate((b,a))
print(c)

[ 6  7  8  9 10  1  2  3  4  5]


In [111]:
a = np.array([1,2,3,4,5,6])
b = np.array_split(a,6)
print(b)

[array([1]), array([2]), array([3]), array([4]), array([5]), array([6])]


In [122]:
a = np.array([1,2,3,2,2,2])
x = np.where(a % 2 == 0)
print(x)

(array([1, 3, 4, 5], dtype=int64),)


In [113]:
#a.sort()
np.sort(a)
print(a[::-1])

[2 2 2 3 2 1]


In [130]:
print(a.reshape((3,2)))
x = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])
print(x.ndim)
print(x)

[[1 2]
 [3 2]
 [2 2]]
3
[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]
