In [ ]:
import  numpy as np

In [ ]:
a = np.array([1,2,3,4])     # Creating Arrays
print(a)
print(type(a))
print(a.ndim)
print(a.dtype)              # Numpy Datatypes

[1 2 3 4]
<class 'numpy.ndarray'>
1
int64


In [ ]:
# Numpy Array Indexing
print(a[0]) 

1


In [ ]:
# Numpy Array Slicing
print(a[-1::-1])

[4 3 2 1]


In [ ]:
a = np.array([1, 2, 3, 4])
a2 = a.copy()
a[3] = 15
print(a)
print(a2)

[ 1  2  3 15]
[1 2 3 4]


In [ ]:
a = np.array([1, 2, 3, 4])
a2 = a.view()
a[3] = 15
print(a)
print(a2)

[ 1  2  3 15]
[ 1  2  3 15]


In [ ]:
a = np.array([1, 2, 3, 4, 5, 6,7,8,9])                            # array_split --> TO SPLIT THE ARRAY INTO 'N' NUMBER OF PARTS
a2 = np.array_split(a, 3)
print(a2[0])
print(a2[1])
print(a2[2])
print(a2)

[1 2 3]
[4 5 6]
[7 8 9]
[array([1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]


In [ ]:
a = np.array([23,56,43,97,85])
print(np.sort(a))

[23 43 56 85 97]


In [ ]:
list = [1,2,3,4,5,6,7]
a = np.array(list)
print(a)
print(type(a))
print(a.ndim)
print(a.dtype)

[1 2 3 4 5 6 7]
<class 'numpy.ndarray'>
1
int64


In [ ]:
a = np.array([1,2,3,4,5,5.4])
print(a)
a = a.reshape(3,2)    # Numpy reshape
print(a)
print(type(a))
print(a.ndim)
print(a.dtype)
print(a.shape)    # Numpy Shape
print(a.size)

[1.  2.  3.  4.  5.  5.4]
[[1.  2. ]
 [3.  4. ]
 [5.  5.4]]
<class 'numpy.ndarray'>
2
float64
(3, 2)
6


In [ ]:
a = np.array([[1, 2, 3, 4, 5], [6, 7, 8, 9, 10]])                 # IN THIS 2-D SLICING 1ST INDEX IS FOR ROWS AND 2ND IS FOR THE ELEMENTS
print(a[0, 1:4])

[2 3 4]


In [ ]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])
arr = np.concatenate((arr1, arr2))
print(arr)


[1 2 3 4 5 6]
